Adding Configuration.md
Real-Dev-Squad/website-status pull request #110
Opened 2021-04-10 17:32 UTC by saxenaaman628

2021-04-11 15:41 UTC, whyDontI commented
I think you meant `CONTRIBUTING.md` not `CONFIGURATION` 😁

2021-04-13 10:19 UTC, swarajpure commented on CONTRIBUTING.md
> +Api contracts can be found [here](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/tasks).
NIT: `API` instead of `Api`

2021-04-14 15:00 UTC, whyDontI requested changes
Good work @saxenaaman628 😃 
Can you also add how we perform GitHub auth using [this](https://github.com/login/oauth/authorize?client_id=c4a84431feaf604e89d1) link?

`https://github.com/login/oauth/authorize?client_id=c4a84431feaf604e89d1`

2021-04-14 15:54 UTC, saxenaaman628 commented
But we are already making local system secure. Do we still need to add those steps.

2021-04-16 16:33 UTC, merged