Added test case and refactored code
Real-Dev-Squad/website-status pull request #1191
Opened 2024-04-14 17:08 UTC by skv93-coder

Date: Apr 14 24

Developer Name: @skv93-coder 

---

## Issue Ticket Number

## Description
This PR implements task status flow on admin site

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
[screen-capture (20).webm](https://github.com/Real-Dev-Squad/website-status/assets/68867418/f0c21744-9323-4091-b88b-92731119ea14)

<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

![Screenshot from 2024-04-14 22-37-50](https://github.com/Real-Dev-Squad/website-status/assets/68867418/67be81db-3db4-44bf-8534-030204618c15)

</details>

## Additional Notes

2024-04-18 14:44 UTC, iamitprakash requested changes

2024-04-19 00:13 UTC, skv93-coder commented on __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
> +    test.skip('Should set new status on click at any option', async () => {
This test case was written for old code. I have converted that code into component and also added multiple test cases for that component. 
I am going to remove this test case via separate PR

2024-04-19 05:39 UTC, palakgupta2712 submitted a review, later dismissed

2024-04-22 17:10 UTC, skv93-coder commented
> <img alt="image" width="139" src="https://private-user-images.githubusercontent.com/61227144/323844504-e27754e9-d35a-4dbf-9285-04bb160deef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDU5MzksIm5iZiI6MTcxMzgwNTYzOSwicGF0aCI6Ii82MTIyNzE0NC8zMjM4NDQ1MDQtZTI3NzU0ZTktZDM1YS00ZGJmLTkyODUtMDRiYjE2MGRlZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE3MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjc0MmEzZTE4ZjVjZmU1OWE2MTBmMzA0ZWY3NTczMTQ3NjhkNjllMzA1ZTJjMjc3YWExNzgwNWJiNTVjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0HwU8852p5KeCxHZg6xwDhKR_lIU2IwoSMpv-Vk3rU4"> Can we improve upon the alignment, if possible?

Sure but currently running on tight deadline so creating a new [issue](https://github.com/Real-Dev-Squad/website-status/issues/1195) for the same

2024-04-23 15:12 UTC, palakgupta2712 approved these changes

2024-04-24 15:47 UTC, mehra-sourav commented on src/constants/constants.ts
> +    'Proceeding further will make task progress 0%.';
A nitpick:
Maybe you can put both the constants you defined under a single object?
`const PROGRESS_MSG = {
         "0": "msg1",
         "100": "msg2" 
 }
`

2024-04-24 15:55 UTC, mehra-sourav approved these changes

2024-04-25 13:56 UTC, skv93-coder commented on __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
> +    test.skip('Should set new status on click at any option', async () => {
Removed so resolving convo

2024-04-26 06:22 UTC, iamitprakash approved these changes

2024-04-26 06:22 UTC, merged