Fix suggestion selection crash bug
Real-Dev-Squad/website-status pull request #1206
Opened 2024-05-18 13:02 UTC by pallabez

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-05-20 02:47 UTC, ardourApeX reviewed
Can you add a working proof here

2024-05-28 16:18 UTC, Achintya-Chatterjee approved these changes

2024-05-28 16:42 UTC, Achintya-Chatterjee reviewed
@pallabez one test is failing, kindly look into that

2024-05-28 18:33 UTC, iamitprakash requested changes
test is failing

2024-05-29 09:11 UTC, Achintya-Chatterjee approved these changes

2024-05-30 02:41 UTC, ardourApeX approved these changes

2024-05-30 03:58 UTC, merged