Add dev flag in fetch task api so done and completed status can be fe…
Real-Dev-Squad/website-status pull request #1207
Opened 2024-05-21 16:22 UTC by skv93-coder

…tched in same API

Date: May 21 2024

Developer Name: @skv93-coder 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-05-24 07:46 UTC, Achintya-Chatterjee approved these changes

2024-05-25 16:46 UTC, iamitprakash commented on src/app/services/tasksApi.ts
> +                    url += '&userFeatureFlag=true';
I guess we only use dev=true

2024-05-25 16:46 UTC, iamitprakash requested changes
comments added

2024-05-25 16:54 UTC, iamitprakash approved these changes

2024-05-25 16:55 UTC, merged