Fix: Assignee text box alignment
Real-Dev-Squad/website-status pull request #1225
Opened 2024-07-31 08:53 UTC by Achintya-Chatterjee

Date: 31 July, 2024

Developer Name: @Achintya-Chatterjee 

---

## Issue Ticket Number

- Closes #1224 
## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-07-31 19:02 UTC, yesyash commented
- can we make the suggestion box width same as the input box?

2024-07-31 19:02 UTC, yesyash requested changes

2024-07-31 19:02 UTC, yesyash commented
- please remove the duplicate input box shown in the video

2024-07-31 19:04 UTC, vinit717 commented on src/components/taskDetails/index.tsx
Can you please break this component

2024-07-31 21:33 UTC, Achintya-Chatterjee commented on src/components/taskDetails/index.tsx
> +                                                    type="text"
@yesyash added, thanks for the suggestion

2024-07-31 21:33 UTC, Achintya-Chatterjee commented
> * can we make the suggestion box width the same as the input box?

@yesyash can you see the video once again ?

2024-07-31 21:35 UTC, Achintya-Chatterjee commented on src/components/taskDetails/index.tsx
I request you to review the `TaskDetails` component one more time after review if you think we need to break this component, I'll break it.

2024-07-31 21:36 UTC, Achintya-Chatterjee commented
> * please remove the duplicate input box shown in the video

@yesyash removed.

2024-07-31 21:41 UTC, Achintya-Chatterjee commented on src/components/taskDetails/index.tsx
> +                                <div className={styles.detailsWithInput}>
@vinit717 changed the class name

2024-08-01 06:29 UTC, vinit717 commented
> > * can we make the suggestion box width the same as the input box?
> 
> @yesyash can you see the video once again ?

![image](https://github.com/user-attachments/assets/91fbc89c-f852-48f2-8fa3-2845403646fb)
still not the same width

2024-08-01 08:58 UTC, Achintya-Chatterjee commented
> > > * can we make the suggestion box width the same as the input box?
> > 
> > 
> > @yesyash can you see the video once again ?
> 
> ![image](https://private-user-images.githubusercontent.com/111434418/354106410-91fbc89c-f852-48f2-8fa3-2845403646fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDI5ODgsIm5iZiI6MTcyMjUwMjY4OCwicGF0aCI6Ii8xMTE0MzQ0MTgvMzU0MTA2NDEwLTkxZmJjODljLWY4NTItNDhmMi04ZmEzLTI4NDU0MDM2NDZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwODU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDQ0ZTRjOWY1ZjU2MzY4M2RmMGQ5Mjc4ZGQ3M2NjYjBjNzE1MmE1MmFhMjc2MzViZTU5ZTUzYzc1NWZmODcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s_XIrJ6k7vY4UXrp5LOKtA2H562jHV50awQyJX3GJjU) still not the same width

@vinit717 fixing it.

2024-08-03 07:47 UTC, Achintya-Chatterjee commented
> > > > * can we make the suggestion box width the same as the input box?
> > > 
> > > 
> > > @yesyash can you see the video once again ?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/111434418/354106410-91fbc89c-f852-48f2-8fa3-2845403646fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDI5ODgsIm5iZiI6MTcyMjUwMjY4OCwicGF0aCI6Ii8xMTE0MzQ0MTgvMzU0MTA2NDEwLTkxZmJjODljLWY4NTItNDhmMi04ZmEzLTI4NDU0MDM2NDZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwODU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDQ0ZTRjOWY1ZjU2MzY4M2RmMGQ5Mjc4ZGQ3M2NjYjBjNzE1MmE1MmFhMjc2MzViZTU5ZTUzYzc1NWZmODcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s_XIrJ6k7vY4UXrp5LOKtA2H562jHV50awQyJX3GJjU) still not the same width
> 
> @vinit717 fixing it.

@vinit717 @yesyash it has been fixed

2024-08-03 18:46 UTC, vinit717 commented
Please increase the test coverage

2024-08-04 18:43 UTC, Achintya-Chatterjee commented
> Please increase the test coverage line 99 and 431

@vinit717 will break the component, so I'm considering tackling this in the next PR.

2024-08-05 12:09 UTC, vinit717 approved these changes

2024-08-05 19:17 UTC, yesyash approved these changes

2024-08-05 19:17 UTC, merged