Added Accordion for challenges
Real-Dev-Squad/website-status pull request #123
Opened 2021-04-16 18:33 UTC by Ankita2002-Fr

@whyDontI @sumitd94

I have added Accordion component for challenges. Please review the WIP PR.

2021-04-24 10:59 UTC, Ankita2002-Fr commented
@whyDontI  @sumitd94 
I have worked on your comments and added all section code in pages/challenges itself. 

Please review the PR!

2021-04-25 14:41 UTC, Ankita2002-Fr commented
@whyDontI @sumitd94 

I have modified the code in pages/challenges.
Please review the PR!

2021-04-26 10:33 UTC, sumitd94 requested changes
Few changes requested please

2021-04-26 10:33 UTC, sumitd94 commented on src/pages/challenges.tsx
> +function renderCardList(challengeSection: challenge['content'], key:string) {
arrow function?

2021-04-26 10:33 UTC, sumitd94 commented on src/pages/challenges.tsx
> +        } else if (!item.is_active) {
No need of `else if` here, if the condition in line no 32 fails, it should directly come here
so,
```javascript
else {...your logic}
```

2021-04-26 10:33 UTC, sumitd94 commented on src/pages/challenges.tsx
> +        }
I think the entire `if else` can be eliminated and you can make use of the `Array filter` method
Try checking this [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

2021-04-26 18:18 UTC, Ankita2002-Fr commented
@whyDontI  @sumitd94  
I have worked on all comments and filtered the challenges.
Please review the PR!

2021-05-18 15:57 UTC, whyDontI approved these changes
LGTM 👍🏽 
Great work @Ankita2002-Fr 🥳

2021-05-18 15:58 UTC, merged