Fix:mine page
Real-Dev-Squad/website-status pull request #1264
Opened 2024-09-19 17:04 UTC by pankajjs

Date:  19 Sep 2024

Developer Name: Pankaj Sha

---

## Issue Ticket Number

#1262 

## Description

Add filter dropdown select and filter logic
Update task card component

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

[screen-capture (2).webm](https://github.com/user-attachments/assets/83bbc675-0b49-4d2d-a9c2-7e955730bcb0)

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/e69ade4a-f36e-430a-bc43-008130267e2a)

</details>

## Additional Notes

2024-09-20 06:37 UTC, vinit717 commented
Did you design doc got approved?

2024-09-20 06:38 UTC, Ayushsanjdev commented
1. PR name doesn't make any sense.
2. Screen recording doesn't play.
@pankajjs

2024-09-20 07:06 UTC, pankajjs commented
> Did you design doc got approved?

Not approved till now. But you asked me to do some changes. I did.

2024-09-20 07:09 UTC, pankajjs commented
> anges. I did.

2024-09-21 08:46 UTC, iamitprakash requested changes
don't we need FF here

2024-09-21 19:19 UTC, vinit717 commented
Where is TDD PR?
as mentioned in the design doc you are following TDD right

2024-09-22 07:43 UTC, pankajjs commented
> Where is TDD PR? as mentioned in the design doc you are following TDD right

I have followed TDD. However I was not aware that I have to raise pr for TDD first.  This pr contains every changes.

2024-09-22 11:58 UTC, pankajjs commented
> don't we need FF here

Added FF.

2024-09-22 12:10 UTC, vinit717 commented on __tests__/Unit/utils/getFilteredTasks.test.ts
> +    };
Can you add this on fixture

2024-09-22 12:58 UTC, pankajjs commented on __tests__/Unit/utils/getFilteredTasks.test.ts
> +    };
Resolved.

2024-09-22 17:29 UTC, iamitprakash approved these changes

2024-09-22 17:52 UTC, vinit717 commented
@pankajjs are we not using the same component for the task tab 
as the UI and functionality are the same

2024-09-22 18:07 UTC, pankajjs commented
> @pankajjs are we not using the same component for the task tab as the UI and functionality are the same
1. Tasks page uses this two components with its own filter logic as it receives data in chunks.
<img width="610" alt="Screenshot 2024-09-22 at 11 33 18 PM" src="https://github.com/user-attachments/assets/ee0277bb-9a45-40e4-8f03-f6b51c4ecbaf">
<img width="433" alt="Screenshot 2024-09-22 at 11 33 32 PM" src="https://github.com/user-attachments/assets/6706a24d-e55d-430d-8635-a7e70efeb222">

2. In Mine page, we receive data at once. Therefore, we are using these two components with its own filter logic.

2024-09-24 16:36 UTC, vinit717 commented
> > @pankajjs are we not using the same component for the task tab as the UI and functionality are the same
> 
> 1. Tasks page uses this two components with its own filter logic inside a component named TasksContent as it receives data in chunks while scrolling.
> 
> <img alt="Screenshot 2024-09-22 at 11 33 18 PM" width="610" src="https://private-user-images.githubusercontent.com/149887791/369708255-ee0277bb-9a45-40e4-8f03-f6b51c4ecbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTYwMzYsIm5iZiI6MTcyNzE5NTczNiwicGF0aCI6Ii8xNDk4ODc3OTEvMzY5NzA4MjU1LWVlMDI3N2JiLTlhNDUtNDBlNC04ZjAzLWY2YjUxYzRlY2JhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjNjYjJiYTVkNTZmOWVkOTc1ZjdlMzA1ZmFjZDNkZWNkMjUxMDViOGVjZmE4YmU5ZjEzMmMyNjVkMWY0ODIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jOc9yJu3lj0BgJaTPV8yVBy40FuLBs-QYOazMB-hmtM"> <img alt="Screenshot 2024-09-22 at 11 33 32 PM" width="433" src="https://private-user-images.githubusercontent.com/149887791/369708257-6706a24d-e55d-430d-8635-a7e70efeb222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTYwMzYsIm5iZiI6MTcyNzE5NTczNiwicGF0aCI6Ii8xNDk4ODc3OTEvMzY5NzA4MjU3LTY3MDZhMjRkLWU1NWQtNDMwZC04NjM1LWE3ZTcwZWZlYjIyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxNjM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTUxZjljOGMwMTQ3YjRlNjI2NTBhMTk1MjdmZjQwOWU5ZGY1ZTMzMDdmODNmNzE5ZDA4MjNlOTc1Y2MwNzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yPuOHyOLjj0LmD3Ds4Y8cFyPPvoM7oLAnhXaokqOh0E">
> 2. In Mine page, we receive data at once. Therefore, we are using these two components with its own filter logic.
> 3. I have made the functionality looks same even the logic is different because of its data fetching technique.

But self API should be paginate then as by this we don't need to create another component for this we can reuse it
can you confirm this with @ankushdharkar

2024-09-24 16:44 UTC, pankajjs commented
@vinit717 Even If we make self API paginated, we need another component to make the filter and search should work as same as Tasks page. Here we are just changing the user's tasks state on filter and search change.

2024-09-25 11:19 UTC, vinit717 commented on src/pages/mine/index.tsx
> +    if (isLoading) return <p>Loading...</p>;
Can we show the shimmer component when loading

2024-09-25 11:20 UTC, vinit717 commented
> @vinit717 Even If we make self API paginated, we need another component to make the filter and search should work as same as Tasks page because the TaskContent is tightly coupled with the hook which returns the tasks list.

But we need to make the component dumb so it get the data and show accordingly 
for now we can merge your PR and If you want,  make the backend API paginated and change the frontend logic accordingly

2024-09-25 11:22 UTC, vinit717 commented on src/utils/getInputValueFromTaskField.ts
> +    if (tab) inputValue += `${getQueryParamTab(tab)} `;
This line is uncover in test

2024-09-25 11:22 UTC, vinit717 commented on src/pages/mine/index.tsx
Improve the test coverage for this file

2024-09-25 11:37 UTC, pankajjs commented
> > @vinit717 Even If we make self API paginated, we need another component to make the filter and search should work as same as Tasks page because the TaskContent is tightly coupled with the hook which returns the tasks list.
> 
> But we need to make the component dumb so it get the data and show accordingly for now we can merge your PR and If you want, make the backend API paginated and change the frontend logic accordingly

We can merge this Pr. For the backend, I will pick it another task.

2024-09-26 16:55 UTC, vinit717 commented on __tests__/Unit/utils/getFilteredTasks.test.ts
> +    };
can you move this to fixture

2024-09-26 17:26 UTC, vinit717 commented on src/pages/mine/index.tsx
can you increase the test coverage for this file

2024-09-27 11:33 UTC, pankajjs commented on src/pages/mine/index.tsx
Before changes
<img width="899" alt="Screenshot 2024-09-26 at 6 20 38 PM" src="https://github.com/user-attachments/assets/ef5e6f20-0866-4239-b961-0f401e7e5661">

After changes
<img width="822" alt="Screenshot 2024-09-27 at 4 55 42 PM" src="https://github.com/user-attachments/assets/963ce464-9e6c-4a6f-bc68-a4f918e5ee53">

2024-09-27 12:41 UTC, vinit717 approved these changes

2024-09-27 13:53 UTC, iamitprakash approved these changes

2024-09-27 14:08 UTC, merged