Updated deprecated /users/self API endpoint to the current working endpoint /users?profile=true
Real-Dev-Squad/website-status pull request #1294
Opened 2024-12-08 20:34 UTC by Hariom01010

Date:  09 Dec 2024

Developer Name: Hariom Vashista

---

## Issue Ticket Number

Fixes: Real-Dev-Squad/todo-action-items#255 repo#3
## Description

The deprecated API endpoint (/users/self) has been replaced by the current in use implementation (/users?profile=true)
### Documentation Updated?

- [ ] Yes
- [X] No

### Under Feature Flag

- [ ] Yes
- [X] No

### Database Changes

- [ ] Yes
- [X] No

### Breaking Changes

- [ ] Yes
- [X] No

### Development Tested?

- [X] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

![Screenshot 2024-12-09 015119](https://github.com/user-attachments/assets/67ad6f54-967d-4435-a775-b23b2e5709b4)
The screenshot shows the working of the site with the /users/self API endpoint (before changes). Response Status: 200 OK
</details>

<details>
<summary>Screenshot 2</summary>

![Screenshot 2024-12-09 015152](https://github.com/user-attachments/assets/ce7021a8-fca9-4efd-b100-799822c4082b)
The screenshot shows the working of the site with the /users?profile=true API endpoint (after the changes). Response Status: 200 OK
</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-12-08 20:37 UTC, Achintya-Chatterjee submitted a review, later dismissed

2024-12-10 06:47 UTC, prakashchoudhary07 requested changes
Tests are failing?

2024-12-10 06:50 UTC, Hariom01010 commented
Will look into it again sir and rerun it on my workspace and try to fix them ASAP

2025-01-04 18:18 UTC, vikasosmium approved these changes

2025-01-04 18:56 UTC, Achintya-Chatterjee approved these changes

2025-01-07 09:55 UTC, merged