created Availability section UI
Real-Dev-Squad/website-status pull request #142
Opened 2021-06-06 10:32 UTC by Pavangbhat

created Availability Panel with responsive design
![1](https://user-images.githubusercontent.com/45538392/120921248-6a1a1400-c6e0-11eb-805b-fdda35275f4b.png)
![2](https://user-images.githubusercontent.com/45538392/120921249-6be3d780-c6e0-11eb-9da3-f7f1a82d6b09.png)

2021-06-16 16:31 UTC, whyDontI requested changes

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/MainSection.tsx
> +  unAssignedTasks: Array<object>;
Define `tasks` type in `interfaces` directory

2021-06-16 16:31 UTC, whyDontI commented on src/pages/availability-panel.tsx
> +        />
Move the code of `MainSection` in this page itself, doesn't make sense to move the **entire** code in a separate component

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/MainSection.tsx
> +      )
Can we figure out some way to not use `nested-ternary`?

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/drag-drop-context/index.tsx
> +import React, { FC, useState } from 'react';
`React` import not required

Expected:
`import { FC, useState } from 'react';`

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/drag-drop-context/index.tsx
> +/* eslint-disable no-alert */
Please refrain from disabling eslint, try to figure out what's the best practice and use it.

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/drag-drop-context/index.tsx
> +  unAssignedTasks: Array<object | any>;
Mention `tasks` type

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/drag-drop-context/index.tsx
> +const getItemStyle = (isDragging: boolean, draggableStyle: any) => {
Use proper type definitions
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/types.md

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/drag-drop-context/index.tsx
> +const onDragEnd = async (result: object | any) => {
Proper type definitions 
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/types.md

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/helper-functions/AssignTask.ts
> +};
No need for the `authToken` argument,
We use `Bearer token` in Staging environment and for the production environment, we use Cookies which doesn't need to be manually added, Cookies automatically go with every request.

2021-06-16 16:31 UTC, whyDontI commented on src/components/availability-panel/helper-functions/AssignTask.ts
> +const AssignTask = async ({ authToken, taskId, assignee }: Props) => {
This is not a component, it's a `function` it should accept normal arguments not the `Props`.
```
const AssignTask = async (authToken: string, taskId: string, assignee: string) => {
    // ...
};
```

2021-06-17 17:11 UTC, Pavangbhat reviewed
Updated UI for production
![1](https://user-images.githubusercontent.com/45538392/122443254-07b4f380-cfbd-11eb-9298-4577368e73d7.png)
![2](https://user-images.githubusercontent.com/45538392/122443261-08e62080-cfbd-11eb-8ef0-426ee1a8156f.png)

2021-06-20 14:15 UTC, sumitd94 reviewed
Added few comments!

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/DroppableComponent.tsx
> +            {unAssignedTasks.map((task, index) => (
NIT: Since we are using only `task.id` and `task.title`, we can destructure the `task` here.

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/index.tsx
> +      if (result.source.droppableId !== result.combine.droppableId) {
can we combine both this `if` condition into one?

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/styles.module.scss
> +  margin: 0 2rem 0 2rem;
NIT: `margin: 0 2rem`

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/styles.module.scss
> +    font-size: 20px;
rem?

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/styles.module.scss
> +  }
some places we are using `rem` and some places `px`. Can we please follow one standard. (rem)

2021-06-20 14:15 UTC, sumitd94 commented on src/components/availability-panel/drag-drop-context/styles.module.scss
> +  }
`.heading, .taskItem, .memberCard { width: 100%; }`

2021-06-23 07:11 UTC, whyDontI approved these changes
Added feature toggle.
Good work @Pavangbhat 🥳 
Some changes are needed, we'll work on them incrementally.

2021-06-23 07:11 UTC, merged