Updated PR loading on bigger screens - issue
Real-Dev-Squad/website-status pull request #179
Opened 2021-08-12 08:33 UTC by rohandhar1234

Works fine for 
1920 x 1080 (FHD)
3840 x 2160 (4K)
7680 x 4320 (8K)

2021-08-12 08:37 UTC, rohandhar1234 commented
1920 x 1080

![fhd](https://user-images.githubusercontent.com/50043126/129165777-b7cd65f4-543a-4c2d-9d9d-cf3abbb88971.png)
4K
![4k](https://user-images.githubusercontent.com/50043126/129165794-fa474612-0cd3-42f6-b1ce-b77561a617b5.png)
8K

![8k](https://user-images.githubusercontent.com/50043126/129165828-f62d3b8c-e4d7-40ec-96ae-5ae7bdc075b2.png)

2021-08-12 10:42 UTC, rohandhar1234 commented
I set the elements that each page displays to 100. This way be it any display size, the PR will always load and the scroll mechanism will work with it. This also works with 65 elements being displayed on each page but I still set it to 100 because this way we can cover a lot of data and can view it on displays greater than 8K

2021-08-13 17:17 UTC, whyDontI requested changes
Technically this solution works 😃 👍🏽 

But, we'll load all 100 PRs even on the small screens.

Can you calculate the number of cards needed using the screen height and card height to fill the screen and request that many cards only?

The formula might look like this,
```
const numberOfCards = ( screenHeight / cardHeight ) * 3
// 3 - is the number of cards in a row 
```

2021-08-24 06:36 UTC, whyDontI requested changes

2021-08-24 06:36 UTC, whyDontI commented on src/components/PullRequestList/index.tsx
> +  const size = Math.floor((global.innerHeight / 147) * 3);
Normally `global` is for the node's runtime and `window` is for browsers. I am not sure how it's working here, I'll try to figure that out.
But for now let's change `global` to `globalThis` so there is no confusion of this sort.

> Recently, globalThis was added to the language, as a standardized name for a global object, that should be supported across all environments. It’s supported in all major browsers.
Refer - https://javascript.info/global-object

2021-08-24 07:17 UTC, closed without merging

2021-08-24 07:26 UTC, rohandhar1234 commented
Closes #174