Content should not hide while loading
Real-Dev-Squad/website-status pull request #191
Opened 2021-08-29 12:41 UTC by anshika29

Before:

https://user-images.githubusercontent.com/60848927/131250660-74ecf3c0-8641-4351-842d-d8fb0a43911c.mp4

After:

https://user-images.githubusercontent.com/60848927/131250679-24307b1c-2ffe-4256-938e-a8386a77222f.mp4

2021-08-30 07:32 UTC, Pavangbhat requested changes

2021-08-30 07:32 UTC, Pavangbhat commented on src/components/availability-panel/drag-drop-context/index.tsx
> -  const [isProcessing, setIsProcessing] = useState<boolean>(false);
We can remove this entire line and occurrence of **setIsProcessing** since we will no longer need to use them

2021-08-30 07:32 UTC, Pavangbhat commented on src/pages/availability-panel.tsx
> -      <span className={classNames.statusMessage}>Loading...</span>
We should be able to see loading message whenever we visit **/availability-panel** for the first time and whenever a task is dropped on a member or vice versa we should not be showing a loading message

2021-08-30 16:57 UTC, Pavangbhat approved these changes
Looks good :+1:

2021-09-01 06:54 UTC, whyDontI approved these changes
LGTM 👍🏽

2021-09-01 06:54 UTC, merged