Dark Mode Feature
Real-Dev-Squad/website-status pull request #219
Opened 2021-11-04 09:30 UTC by abhinav1590

Closes #205 

https://user-images.githubusercontent.com/86315672/140290064-bb52103d-c6df-4fbd-b806-16973069e073.mp4

2021-11-04 09:44 UTC, harshith-venkatesh requested changes

2021-11-04 09:44 UTC, harshith-venkatesh commented on package.json
> +    "styled-components": "^5.3.3",
Why did you install `styled-components` when we already have `sass`

2021-11-04 09:44 UTC, harshith-venkatesh commented on src/components/Layout/index.tsx
> +import { ThemeProvider } from 'styled-components';
Look for the way where you can build `ThemeProvider` without styled-component please

2021-11-04 09:44 UTC, harshith-venkatesh commented on src/components/dark-theme/globalStyles.js
> +import { createGlobalStyle } from 'styled-components';
This can be handled without `styled-components`

2021-12-25 16:53 UTC, whyDontI commented
Was stale for too long.

2021-12-25 16:53 UTC, closed without merging