Specific type description for participants and content done
Real-Dev-Squad/website-status pull request #23
Opened 2020-12-20 11:16 UTC by Khanjan04

Changed the type description for participants and content.

2020-12-20 11:18 UTC, Khanjan04 commented
Please have a look to these changes. And let me know if there is any suggestion.

2020-12-20 11:30 UTC, whyDontI requested changes
Can we fix formatting for all the types/interface definitions?

2020-12-20 11:30 UTC, whyDontI commented on src/components/challenges/active.tsx
> +    participants: {user_id: string,
Can we move this `user_id` on new line?

2020-12-20 11:30 UTC, whyDontI commented on src/components/challenges/active.tsx
> +    is_user_subscribed: number;
Can we fix the formatting?

2020-12-20 11:31 UTC, Khanjan04 commented on src/components/challenges/active.tsx
> +    participants: {user_id: string,
Sure. let me do that

2020-12-20 11:31 UTC, Khanjan04 commented on src/components/challenges/active.tsx
> +    is_user_subscribed: number;
Let me do that

2020-12-20 11:38 UTC, Khanjan04 commented
Have done required changes. Please have a look.

2020-12-20 13:12 UTC, Khanjan04 commented
Done.

2020-12-21 13:49 UTC, Khanjan04 commented
Done Nikhil. Check it once

2020-12-21 13:50 UTC, whyDontI approved these changes
Great work @Khanjan04 🥳 🔥

2020-12-21 13:51 UTC, Khanjan04 commented
Can I merge PR?

2020-12-21 13:52 UTC, merged