Added buttons to enable admins to edit task
Real-Dev-Squad/website-status pull request #253
Opened 2022-02-14 05:09 UTC by Kshashank99

Closes #222 
### What is the change?

Added buttons to allow superuser|| admin to re-route to `?edit=true`  and `?dev=true`

### Is it a bug?

- No

### \*Dev Tested?

- [x] Yes
- [ ] No

### \*Tested on:

#### Platforms

- [x] Web

#### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox

### Before / After Change Screenshots

> For visual or interaction changes. Can be video / screenshot.

https://user-images.githubusercontent.com/64394213/153803603-3651b11b-c47e-4ad6-bc32-26dbe3c1fde4.mp4

2022-02-14 05:31 UTC, DeRaowl requested changes

2022-02-14 05:31 UTC, DeRaowl commented on src/components/Layout/Layout.module.scss
> +  right: 0;
As right is used below, can you remove this line

2022-02-14 05:31 UTC, DeRaowl commented on src/components/Layout/Layout.module.scss
> +  right:250px;
Can you use relative units?

2022-02-14 05:31 UTC, DeRaowl commented on src/components/Layout/Layout.module.scss
> +// .links{
Commented Code can be removed.

2022-02-14 05:31 UTC, DeRaowl commented on src/components/Layout/index.tsx
> +  let elementRef  = useRef();
useRef created but never used

2022-02-14 05:31 UTC, DeRaowl commented on src/components/Layout/index.tsx
> +import { FC, ReactNode, useEffect, useRef, useState } from 'react';
useRef imported and never used

2022-02-15 14:40 UTC, Pavangbhat requested changes
I have commented few suggestions, please have a look

2022-02-15 14:40 UTC, Pavangbhat commented on src/components/Layout/Layout.module.scss
> +  // padding-right:25%;
please remove comments in the code

2022-02-15 14:40 UTC, Pavangbhat commented on src/components/Layout/index.tsx
> +const SELF_URL = `${process.env.NEXT_PUBLIC_BASE_URL}/users/self`;
Please make use of constants from here 👇 
https://github.com/Real-Dev-Squad/website-status/blob/develop/src/components/constants/url.js

2022-02-15 14:40 UTC, Pavangbhat commented on src/components/Layout/index.tsx
> +const { SUCCESS, ERROR } = ToastTypes;
Please move this line to the end of the import statements

2022-02-15 14:40 UTC, Pavangbhat commented on src/components/Layout/index.tsx
> +                src="/add.png"
I think we can remove **/** here

2022-02-15 14:40 UTC, Pavangbhat commented on src/components/Layout/index.tsx
> +                src="/pencil.png"
I think we can remove **/** here

2022-06-13 17:34 UTC, Neha requested changes

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/Layout.module.scss
>    color: #E30464;
This should move to the variable file

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/Layout.module.scss
> +  float:right;
Do not use `FLOAT`

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/Layout.module.scss
> +  right:250px;
No, relative units should not be used.

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/index.tsx
> +  useEffect(() => {
Move this to a separate function (util). Keep the component only for the single task it is responsible for

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/index.tsx
>            {navBarContent('Stale PRs', '/stale-pr', router.pathname === '/stale-pr')}
Move hard-coded content such as _Stale PRs_ to the `constant` file

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/index.tsx
> +
`Routing` should be move to the separate component/file

2022-06-13 17:34 UTC, Neha commented on src/components/Layout/index.tsx
> +                height= "25px"
Move this to the `constant` file

2023-11-10 09:59 UTC, closed without merging