making ds section responsive
Real-Dev-Squad/website-status pull request #26
Opened 2020-12-23 10:47 UTC by saishankarmanugula

Made changes to make DS section responsive

2020-12-28 15:21 UTC, saishankarmanugula commented
I have made additional changes by removing more margin around cards. Please find below screenshots and let me know if any changes are needed.

![image](https://user-images.githubusercontent.com/11243646/103224761-58249000-494e-11eb-9821-129c0e945fa7.png)

![Uploading image.png…]()

2020-12-28 18:05 UTC, whyDontI requested changes

2020-12-28 18:05 UTC, whyDontI commented on src/styles/index.scss
> +  margin: 0 2em;
This will affect other cards on the `Tasks` page.
Can we try some other approach?

2020-12-29 14:41 UTC, whyDontI approved these changes
Great work @saishankarmanugula 👍🏽

2020-12-29 14:41 UTC, merged