Fix multiple authorization checks
Real-Dev-Squad/website-status pull request #307
Opened 2022-09-08 18:31 UTC by whyDontI

- [x] Removed error toast which wasn't necessary for Non-Admin users
- [x] Removed useEffect authorization on card component, used `shouldEdit` prop passed from index page
- [x] Lint fixes on the edited pages

2022-09-15 03:53 UTC, Maheima requested changes
There are a lot of unnecessary addition of space-related changes in this PR. Please fix those so, it becomes cleaner and not distracting

2022-09-15 03:53 UTC, Maheima commented on src/components/tasks/card/index.tsx
> -  const context = useAppContext() ;
Can you please fix these unnecessary changes that show up here?

2022-09-17 04:51 UTC, ankushdharkar requested changes

2022-09-17 04:51 UTC, ankushdharkar commented on src/pages/index.tsx
> -      }
Should we not convert the toast to maybe a console error at least?

2022-09-27 17:26 UTC, whyDontI commented
Same issue is being solved in [this](https://github.com/Real-Dev-Squad/website-status/pull/306) PR, should we close this one?

2022-10-21 06:30 UTC, akshay1502 commented
Closing this PR, https://github.com/Real-Dev-Squad/website-status/pull/306 resolved the issue.

2022-10-21 06:30 UTC, closed without merging