Integrated stale pull requests API
Real-Dev-Squad/website-status pull request #38
Opened 2021-01-07 08:09 UTC by adnanraghib1308

Integrated stale pull requests API. This is solution for the issue #28 . See Screenshot

![Screenshot 2021-01-07 at 1 38 15 PM](https://user-images.githubusercontent.com/56679676/103867634-b50e0c00-50ed-11eb-9ed4-9ff9302b1e8d.jpg)

2021-01-07 12:44 UTC, whyDontI requested changes
Requested some little changes 👍🏽

2021-01-07 12:44 UTC, whyDontI commented on src/components/pullRequests/card/card.module.scss
> +  margin-bottom: 2em;
Please use px as a unit for border, margin, padding, these metrics are not dependent on the parents/roots font-size.
https://css-tricks.com/rems-ems/

2021-01-07 12:44 UTC, whyDontI commented on src/components/pullRequests/card/card.module.scss
> +  padding: 0.5rem 2rem;
Please use px as a unit for border, margin, padding, these metrics are not dependent on the parents/roots font-size.
https://css-tricks.com/rems-ems/

2021-01-07 12:44 UTC, whyDontI commented on src/components/pullRequests/card/card.module.scss
> +
Can we remove blank lines?

2021-01-07 12:44 UTC, whyDontI commented on src/components/pullRequests/section/index.tsx
> +  })
Cards will re-render and reinitialized every time `Section` updates
Can we make it a separate function and pull it out of the `Section` function definition?

2021-01-07 14:07 UTC, adnanraghib1308 commented
Made the required changes. Please review again. @whyDontI

2021-01-07 18:29 UTC, whyDontI requested changes
As per your current design. All the cards are stacked vertically which leaves a lot of space vacant in Desktop view.
Vertical cards are good for devices with small screens, but we should use the space in Desktop mode.

Can you make the cards display horizontally in 2 or columns, similar to what we have done in the `Tasks` tab?

Thanks
Let me know if you need any help 😄 👍🏽

2021-01-07 18:39 UTC, sumitd94 requested changes

2021-01-07 18:39 UTC, sumitd94 commented on src/components/pullRequests/card/index.tsx
> +        <a href = {url} className={classNames.links} target = "_blank">
Please make sure you add a `noreferrer` attribute for `href` tags.

2021-01-08 04:55 UTC, adnanraghib1308 commented
@whyDontI @sumitd94 Done with changes. Please review again

2021-01-08 07:05 UTC, sumitd94 submitted a review, later dismissed

2021-01-08 07:05 UTC, sumitd94 commented on src/components/pullRequests/card/card.module.scss
> +}
NIT : Here you can use the shorthand property like `margin: 0 60px 30px 60px;`

2021-01-08 07:05 UTC, sumitd94 commented on src/components/pullRequests/card/card.module.scss
> +  flex-direction: row;
NIT : By default when you use `display: flex` the direction is `row` . so `flex-direction: row` is not necessary.

2021-01-08 07:05 UTC, sumitd94 commented on src/components/pullRequests/card/card.module.scss
> +}
NIT: you can even add a `outline: none` property.
Take a look here what this is useful for.https://developer.mozilla.org/en-US/docs/Web/CSS/outline

2021-01-09 12:30 UTC, whyDontI approved these changes
Good work @adnan1308 👍🏽

2021-01-09 12:30 UTC, merged