Refactored updateTasksStatus.ts
Real-Dev-Squad/website-status pull request #488
Opened 2023-04-11 17:59 UTC by endeavourmonk

2023-04-11 18:42 UTC, bhtibrewal submitted a review, later dismissed

2023-04-11 18:42 UTC, bhtibrewal reviewed
LGTM

2023-04-15 15:18 UTC, bhtibrewal requested changes

2023-04-15 15:18 UTC, bhtibrewal commented on src/helperFunctions/updateTasksStatus.ts
> +        completed = 'COMPLETED',
```
return tasks.map((taskItem) => {
       { ...taskItem, status :
            Status[taskList[index].status as keyof typeof Status]}
    });
```

2023-04-21 16:54 UTC, endeavourmonk commented on src/helperFunctions/updateTasksStatus.ts
> +        completed = 'COMPLETED',
@bhtibrewal updated please review

2023-05-05 11:02 UTC, bhtibrewal approved these changes
LGTM

2023-05-05 12:37 UTC, RitikJaiswal75 reviewed
I tried running your PR locally

This is what it shows

![image](https://user-images.githubusercontent.com/57758447/236459214-6276e7fa-6618-43b0-9ae0-e010a8435499.png)

2023-06-15 17:03 UTC, closed without merging