wrote tests+resolved queries
Real-Dev-Squad/website-status pull request #558
Opened 2023-05-14 08:19 UTC by sonai99

Wrote the RTK query for CHALLENGES_URL and replaced the useFetch implementation
Also wrote the test for it

![image](https://github.com/Real-Dev-Squad/website-status/assets/62872224/0bea5d1f-de78-4a00-972c-a4194187a374)

![image](https://github.com/Real-Dev-Squad/website-status/assets/62872224/283bff8e-a157-4a74-8c32-2f12d0ee297e)

2023-05-14 08:20 UTC, sonai99 commented
had to create a new PR with suggestions from the previous one + wrote the test 
cc @bhtibrewal @Pratiyushkumar @kotesh-arya

2023-05-14 13:46 UTC, bhtibrewal commented on __tests__/Unit/hooks/challengesApi.test.tsx
> +        console.log(nextResponse.data);
remove this console log

2023-05-14 13:46 UTC, bhtibrewal commented on src/app/services/challengesApi.ts
> +      transformResponse: (response: ChallengesQueryResponse) => {
I can't find the sense of transformResponse here if you are sending the response as it is

2023-05-14 15:21 UTC, iamitprakash commented on src/pages/challenges/index.tsx
> +                        ) : isError ? (
can you please change to text like-- "Something Went Wrong, Please Contact Admin !"

2023-05-17 08:47 UTC, sonai99 commented on src/app/services/challengesApi.ts
> +                return response.challenges;
@bhtibrewal please review this one

2023-05-17 12:15 UTC, bhtibrewal commented on src/pages/challenges/index.tsx
>                  setFilteredChallenge(challengeMap);
I think it would be if do this filtering in the `tranformResponse` of the RTK Query itself

2023-05-17 12:16 UTC, bhtibrewal reviewed
Added a comment everything else seems okay

2023-05-20 06:31 UTC, sonai99 commented on src/app/services/challengesApi.ts
> +                return challengeMap;
@bhtibrewal please check
i have done the filtering in the query itself

2023-05-20 06:42 UTC, Pratiyushkumar requested changes
Please write the test cases also

2023-05-20 06:44 UTC, sonai99 commented
> Please write the test cases also
@Pratiyushkumar 
that i have done in a previous commit only.
Check https://github.com/Real-Dev-Squad/website-status/pull/558/commits/531e9e87ed6a648f9644c9b5012aa2d0e23f043f

2023-05-21 09:19 UTC, bhtibrewal submitted a review, later dismissed
good work @sonai99  looks okay to me

2023-05-21 13:28 UTC, Pratiyushkumar approved these changes
good work @sonai99, looks good to me

2023-05-22 12:55 UTC, sonai99 commented
@bhtibrewal I have resolved the build fail
It was due to a check missing in the rtk query.

2023-05-22 14:13 UTC, bhtibrewal approved these changes
Looks okay to me

2023-06-01 13:37 UTC, sonai99 commented
@bhtibrewal can you please have a look at the latest commit.
Last time build failed due to the test failing, i have corrected it and its passing on local now.

2023-06-18 05:06 UTC, sonai99 commented
@Pratiyushkumar Could you please have a look at this, its still awaiting approval. Not sure if i am required to do anything more on this.

2023-06-18 14:33 UTC, Pratiyushkumar submitted a review, later dismissed

2023-06-19 12:39 UTC, sonai99 commented
@Pratiyushkumar i have resolved the queries

2023-06-19 15:44 UTC, Pratiyushkumar submitted a review, later dismissed
LGTM

2023-06-21 06:59 UTC, sonai99 commented
@kotesh-arya  / @shubhamsigdar1 can you please review this, need one more approval, its getting really delayed.

2023-06-22 16:38 UTC, Pratiyushkumar approved these changes
LGTM

2023-06-24 06:01 UTC, sonai99 commented
@iamitprakash  / @bhtibrewal  
General reminder that this PR is still awaiting approval.

2023-06-29 08:01 UTC, sonai99 commented
@bhtibrewal  any reasons this hasn't been approved yet?
I got the approval from @Pratiyushkumar, just need one more.

2023-07-01 15:50 UTC, bhtibrewal approved these changes
LGTM, nice work @sonai99

2023-07-01 15:50 UTC, merged