Adding Shimmer
Real-Dev-Squad/website-status pull request #57
Opened 2021-01-20 14:48 UTC by aman7870

https://user-images.githubusercontent.com/26053172/105190646-3b016c80-5b5c-11eb-89ee-2968240a5d49.mp4

adding the shimmer feature. I have used setTimeout() for delaying the data for 3sec.

2021-01-20 15:48 UTC, whyDontI requested changes
Nice work @aman7870 🥳 
Requested some little changes.

2021-01-20 15:48 UTC, whyDontI commented on src/pages/openPRs.tsx
> +      }, 3000);
setTimeout is not required, we can remove this.

2021-01-20 15:48 UTC, whyDontI commented on src/pages/openPRs.tsx
> +      </>
https://www.loom.com/share/20569612ef244c58a6599e6c7bc170cf

2021-01-23 16:18 UTC, aman7870 commented
did the changes and removed the function getLoading(). Please Review

2021-01-24 20:09 UTC, whyDontI approved these changes
Great work @aman7870 🥳

2021-01-24 20:09 UTC, merged

2021-01-25 01:33 UTC, aman7870 commented
Thanks for reviewing and merging the PR