fixed task card long title (after adding feature-flag) (#595)
Real-Dev-Squad/website-status pull request #600
Opened 2023-05-30 12:30 UTC by shubhamsigdar1

Date:
Developer Name:

PR Number(s):-
Issue Ticket Number:-

Backend changes
Yes
No

Frontend Changes
Yes
No

Database changes
Yes
No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Yes
No

Deployment notes
Any special instructions for the deployment

Tested in staging
Yes
No

List of PRs going in this Sync.

Also attach their screenshots.

2023-06-01 04:23 UTC, RitikJaiswal75 commented
please add the screenshot of the width fix with the URL bar showing, else how will I know if it is on staging or local

2023-06-02 16:23 UTC, khushi818 commented
> please add the screenshot of the width fix with the URL bar showing, else how will I know if it is on staging or local

yup I have added

2023-06-02 16:39 UTC, vinit717 commented
For task Dependency 
![image](https://github.com/Real-Dev-Squad/website-status/assets/111434418/a5334d87-431a-4b31-b288-d6f65f7a95dd)
![image](https://github.com/Real-Dev-Squad/website-status/assets/111434418/2c5ed088-3815-4067-b38f-17e0ccb321ab)

2023-06-02 20:33 UTC, RitikJaiswal75 commented
** REFACTOR: API calls for TaskDetails Page Migrated to RTK Query **
Please use the video for above in staging not on dev

2023-06-02 20:36 UTC, iamitprakash requested changes

2023-06-02 20:36 UTC, iamitprakash commented on src/app/services/taskDetailsApi.ts
> +export const taskDetailsApi = api.injectEndpoints({
updateTaskDetails mutation is incorrectly using the PATCH method, when it should be using the PUT method. The PATCH method is used to update a specific resource, while the PUT method is used to replace a resource entirely. In this case, we want to replace the entire task details resource, so we should be using the PUT method.

2023-06-03 15:36 UTC, merged