Add userStatusFlag for changing status based on task
Real-Dev-Squad/website-status pull request #692
Opened 2023-07-06 01:47 UTC by heyrandhir

### Issue:
Parent Ticket Id - https://github.com/Real-Dev-Squad/website-backend/issues/1184

### Description:
Add userStatusFlag for changing status based on task

### Anthing you would like to inform the reviewer about:

### Dev Tested:
- [x] Yes

### Images/video of the change:

### Follow-up Issues (if any)

2023-07-06 04:59 UTC, vinit717 approved these changes

2023-07-06 23:52 UTC, ankushdharkar requested changes
This doesn't allow user to optionally opt in to using the new feature. Could we follow the pattern of FFs from other instances in the code pleae?

2023-07-09 06:43 UTC, bhtibrewal commented on src/app/services/tasksApi.ts
> +                    : `tasks/${id}`,
```suggestion
                url: `tasks/${id}`,
                params: {userStatusFlag}
```

2023-07-09 13:26 UTC, heyrandhir commented
Closing this as by mistake push unwanted changes. will raise a new PR

2023-07-09 13:26 UTC, closed without merging