FEATURE : Add pagination in tasks page
Real-Dev-Squad/website-status pull request #697
Opened 2023-07-08 10:36 UTC by sahsisunny

### Issue:

### Description:

### Anthing you would like to inform the reviewer about:

### Dev Tested:
- [ ] Yes

### Images/video of the change:

### Follow-up Issues (if any)

2023-07-10 14:04 UTC, bharati-21 commented on src/app/services/tasksApi.ts
> +            }
Please define a type separately

2023-07-10 14:34 UTC, bharati-21 commented on src/components/tasks/TasksContent.tsx
> +        nextPage: nextPage,
NIT: please use shorthand

2023-07-10 14:47 UTC, bharati-21 commented on src/pages/mine/index.tsx
> +function CardList({ tasks }: { tasks: TasksResponseType }) {
please destructure tasks from tasks props

2023-07-11 08:18 UTC, sahsisunny commented on src/pages/mine/index.tsx
> +    if (tasks)
Done

2023-07-12 15:47 UTC, Pratiyushkumar commented on src/components/tasks/RenderTasksList.tsx
> +
remove console.log please

2023-07-12 23:04 UTC, sahsisunny commented on src/components/tasks/TasksContent.tsx
> +                </div>
Not needed for these small elements

2023-07-12 23:05 UTC, sahsisunny commented on src/components/tasks/TasksLoader/tasksloader.module.scss
> +    background-color: #e3e3e3;
Done

2023-07-12 23:11 UTC, sahsisunny commented on src/app/services/tasksApi.ts
> +            }
Done

2023-07-13 11:39 UTC, Pratiyushkumar submitted a review, later dismissed
LGTM

2023-07-14 05:31 UTC, bharati-21 requested changes

2023-07-14 08:16 UTC, sahsisunny commented on src/components/tasks/TasksContent.tsx
> +            {dev === 'true' ? (
I didn't get

2023-07-14 08:20 UTC, sahsisunny commented on src/components/tasks/TasksContent.tsx
> +            {dev === 'true' ? (
Done

2023-07-14 08:22 UTC, sahsisunny commented on src/components/tasks/TasksLoader/index.tsx
> +                <div className={classNames.line}></div>
As per the discussion I am creating the referenced issue to skeleton look like task skeleton.

2023-07-14 08:26 UTC, Pratiyushkumar approved these changes
LGTM

2023-07-14 10:34 UTC, vinit717 approved these changes
LGTM

2023-07-14 13:59 UTC, bharati-21 requested changes

2023-07-14 13:59 UTC, bharati-21 commented on src/components/PaginationButton/index.tsx
What I meant by create a separate component for button is a generic button component that takes text, change handler as props.

This is fine for now. But once this PR is done, we should create a generic button component and re-use it here.
That way you can create two buttons
```
<Button text="Prev" onClickHandler={handlePrevClicked} />
<Button text="Next" onClickHandler={handleNextClicked} />
```

2023-07-14 13:59 UTC, bharati-21 commented on src/components/PaginationButton/index.tsx
> +export default PaginationButton;
Kindly write test for this component.

2023-07-14 14:10 UTC, bharati-21 approved these changes

2023-07-14 14:46 UTC, merged