feat: idle members UI changes created
Real-Dev-Squad/website-status pull request #80
Opened 2021-03-01 18:52 UTC by harshith-venkatesh

2021-03-01 19:12 UTC, harshith-venkatesh commented
https://www.loom.com/share/d4c18cabffb94fdcb4c586ef1f120865

2021-03-01 19:15 UTC, harshith-venkatesh commented
![Uploading image.png…]()

2021-03-01 19:15 UTC, harshith-venkatesh commented
![image](https://user-images.githubusercontent.com/44545218/109546759-9c6c1200-7af0-11eb-84d2-c3f50660d206.png)

2021-03-01 23:20 UTC, sumitd94 requested changes
Few NIT Comments, rest all looks good to me. Thanks.

2021-03-01 23:20 UTC, sumitd94 commented on src/components/idleMembers/card/index.tsx
> +  const imageGenerator = (name: string) => `https://raw.githubusercontent.com/Real-Dev-Squad/website-static/main/members/${name}/img.png`;
I think we have this URL defined in the .env file, why not take it from there

ref - https://github.com/Real-Dev-Squad/website-status/blob/develop/.env

2021-03-01 23:20 UTC, sumitd94 commented on src/components/idleMembers/section/index.tsx
> +          <div className={classNames.cardContainer}>{cards(content)}</div>
NIT: we can rename `cards` to `renderCards`
makes the purpose of the function clear.

2021-03-01 23:20 UTC, sumitd94 commented on src/components/idleMembers/section/section.module.scss
> +  flex-direction: row;
NIT: Not needed, by default `display: flex,` assumes the direction to be row.

2021-03-03 09:45 UTC, sumitd94 submitted a review, later dismissed
Looks good to me, Thanks

2021-03-03 18:46 UTC, whyDontI requested changes
Nice work @harshith-venkatesh 😃 

A little change,
can you center the cards?

2021-03-13 11:01 UTC, harshith-venkatesh commented
@whyDontI @sumitd94 can we merge this
It is still pending

2021-03-14 14:51 UTC, whyDontI approved these changes
Nice work @harshith-venkatesh 🥳

2021-03-14 14:51 UTC, merged