Fix :Github link to display in task details page.
Real-Dev-Squad/website-status pull request #827
Opened 2023-08-19 18:07 UTC by kapillondhe

### Issue:
In Tasks tab, when clicked on task title. Task detail page is displayed.
In task details page NA is being displayed for Link. It should display the button to open GitHub Issue link.

Screenshot before these changes :
Link property displayed as NA.
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/1855ab2e-94e1-44d2-90f4-7a1fd590ae63)

### Description:
HTML URL of the GitHub issue is sent in the request body while creating tasks from the issue. Backend changes are done to store the GitHub issue HTML URL in the tasks database. UI changes are done to add a button when the Git issue link is present. After clicking on the button, the respective GitHub issue link will open in a new tab.

### Anything you would like to inform the reviewer about:
Backend changes are also required for this fix. PR 1428 raised in website-backend.

### Dev Tested:
-  [x] Yes
-  [ ] No

### Images/video of the change:
Link property displayed as a button.
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/04cd69a4-85bb-4a6a-971a-e83fc99626b4)

### Test stat:

Before: 
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/86ca54af-8d15-4fba-be37-cb68ee7de6bc)

After : 
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/d72cbd77-d799-4379-ac12-0ff4bd193275)

### Follow-up Issues (if any)
No

2023-08-22 01:48 UTC, sahsisunny commented
Is it possible to display only the icon on the link issue button without any background color?

2023-08-22 08:24 UTC, AnjaliDeshwani reviewed
The size of the Link icon seems a little bigger to me. If possible, can it be aligned on the same line as the Link label and not occupy the next line

2023-08-23 03:13 UTC, kapillondhe commented
> Is it possible to display only the icon on the link issue button without any background color?

@sahsisunny  Yes, a button without a background color (White) can be displayed. What should be the color on the hover for the button?

2023-08-23 04:03 UTC, kapillondhe commented
> The size of the Link icon seems a little bigger to me. If possible, can it be aligned on the same line as the Link label and not occupy the next line. Though rest code looks good to me.

@AnjaliDeshwani  Sure, I have updated it to align in the same line and reduced the size of the button. Thanks 
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/4b54ffe8-ebc1-4f62-8691-b6d8ae71f03d)

2023-08-23 04:07 UTC, kapillondhe commented
> > Is it possible to display only the icon on the link issue button without any background color?
> 
> @sahsisunny Yes, a button without a background color (White) can be displayed. What should be the color on the hover for the button?

@sahsisunny I have updated the code. Please find below the image for the button display over hover. Please let me know if you have any further suggestions.
![image](https://github.com/Real-Dev-Squad/website-status/assets/41846637/36ed6477-a5c6-44cd-af4e-4ffb8d95fd4a)

2023-08-25 05:52 UTC, vinit717 commented on __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
> +            window.open = originalOpen;
Remove comments

2023-08-25 05:52 UTC, vinit717 commented on public/openInNewTab.svg
change the file name

2023-08-25 05:53 UTC, vinit717 commented
Can you add a video for how it work and how it look like in different screen size

2023-08-25 16:50 UTC, kapillondhe commented on public/openInNewTab.svg
Changed the file name to openLink.svg. Please feel free to suggest a new name.

2023-08-25 16:51 UTC, kapillondhe commented on __tests__/Unit/Components/Tasks/TaskDetails.test.tsx
> +            window.open = originalOpen;
Sure. Removed the comments.

2023-08-25 16:52 UTC, kapillondhe commented
> Can you add a video for how it work and how it look like in different screen size

Sure. Added the video in the PR description.

2023-08-28 04:13 UTC, sahsisunny approved these changes

2023-08-28 05:03 UTC, vinit717 commented on public/openInNewTab.svg
githubLink.svg

2023-08-28 05:05 UTC, vinit717 commented
![image](https://github.com/Real-Dev-Squad/website-status/assets/111434418/de610d67-7e64-4aa4-9b4d-aeb3198cade0)
Why in this button we have 2 icons why can't we use only single icon which should be github icon only?

2023-08-28 05:40 UTC, kapillondhe commented on public/openInNewTab.svg
Changed the name to githubLink.svg. Thanks.

2023-08-28 07:01 UTC, kapillondhe commented
> ![image](https://user-images.githubusercontent.com/111434418/263597959-de610d67-7e64-4aa4-9b4d-aeb3198cade0.png) Why in this button we have 2 icons why can't we use only single icon which should be github icon only?

@vinit717 Both of these icons suggest that we are opening a GitHub link. If we have only the GitHub icon, it will not represent the action after clicking. Please let me know if you don't find this reasoning acceptable; I can change this to a single icon.

2023-08-29 04:39 UTC, vinit717 commented
> > ![image](https://user-images.githubusercontent.com/111434418/263597959-de610d67-7e64-4aa4-9b4d-aeb3198cade0.png) Why in this button we have 2 icons why can't we use only single icon which should be github icon only?
> 
> @vinit717 Both of these icons suggest that we are opening a GitHub link. If we have only the GitHub icon, it will not represent the action after clicking. Please let me know if you don't find this reasoning acceptable; I can change this to a single icon.

It's evident that this link should follow the same standard as other clickable links, utilizing a single icon to represent its nature as a GitHub link. This consistency in iconography simplifies the user experience and aligns with established design principles

2023-08-30 06:56 UTC, vinit717 approved these changes

2023-08-30 16:48 UTC, sahsisunny approved these changes

2023-08-31 06:13 UTC, vinit717 requested changes

2023-08-31 06:13 UTC, vinit717 commented on src/components/taskDetails/Details.tsx
Please make your code changes behind the feature flag

2023-09-01 04:40 UTC, vinit717 approved these changes

2023-09-01 05:00 UTC, sahsisunny approved these changes

2023-09-04 19:24 UTC, rohan09-raj commented on src/components/taskDetails/task-details.module.scss
> +    padding-right: 8px;
Why we have included `padding` and then padding-left /right, only one has to be applied here

2023-09-04 19:24 UTC, rohan09-raj commented on src/components/taskDetails/index.tsx
> +                                        }
Can we please single line for this ?

2023-09-04 19:36 UTC, rohan09-raj commented on src/components/taskDetails/Details.tsx
Can we please utlizie this design, currently it's cluttered with icons?
![image](https://github.com/Real-Dev-Squad/website-status/assets/78433013/8ffeecc2-b263-4ce5-8c41-a4e171669497)

Text Color in Variant #2 is #1d1283

2023-09-04 19:37 UTC, rohan09-raj commented on src/components/taskDetails/Details.tsx
> +                    <button
Also, this can be an anchor tag as it's better if we have links

2023-09-05 01:10 UTC, kapillondhe commented on src/components/taskDetails/Details.tsx
@sahsisunny @vinit717 do you agree with this? please let me know your suggestions.

2023-09-05 14:26 UTC, sahsisunny commented on src/components/taskDetails/Details.tsx
Is this currently under a feature flag?  If so, we should consider making the change in the next PR since it's been open for some time.  I suggest that if Rohan agrees with me then this PR will be merged ASAP and a reference issue is created to address similar suggestions.

2023-09-05 14:54 UTC, kapillondhe commented on src/components/taskDetails/Details.tsx
@sahsisunny Yes this is under a feature flag. @rohan09-raj do you agree? I will address your comments in the follow-up PR.

2023-09-06 13:47 UTC, rohan09-raj commented on src/components/taskDetails/Details.tsx
Sure no issues but yeah till the time you were waiting for the opinion, this minor change could have completed by now

2023-09-07 01:16 UTC, merged