REFACTOR: replace idle members(users) api with existing idle-users api
Real-Dev-Squad/website-status pull request #946
Opened 2023-10-14 23:59 UTC by kotesh-arya

### Issue:
- [ ] https://github.com/Real-Dev-Squad/website-members/issues/547
### Description:
 The `/members/idle` route which was returning only member-role containing users is replaced with `/users/search?state=IDLE`
### Design Doc:
https://docs.google.com/document/d/1xvllP-qyZBAHFzp5Oh-7d-bTh_JHX7Ps_KsOTUSkPYE/edit?usp=sharing

### Locally Tested:
- [x] Yes

### Images/video of the change:
**Before:**
![image](https://github.com/Real-Dev-Squad/website-status/assets/69259490/005ffc95-efca-4fa6-b8ca-ddc6a05129b4)

**After:**
![image](https://github.com/Real-Dev-Squad/website-status/assets/69259490/f5eea482-d464-4091-aacf-dd1952360eaa)

### Test Coverage Stats:
![image](https://github.com/Real-Dev-Squad/website-status/assets/69259490/99996156-92e1-45b8-8239-4fd6393349a5)

![image](https://github.com/Real-Dev-Squad/website-status/assets/69259490/303f9db8-f66b-4956-93a3-c5c8221f83e0)

### Follow-up Issues (if any)

2023-10-16 18:03 UTC, iamitprakash requested changes

2023-10-16 19:21 UTC, iamitprakash approved these changes

2023-10-16 19:25 UTC, Achintya-Chatterjee approved these changes

2023-10-16 19:39 UTC, anishpawaskar approved these changes
LGTM

2023-10-16 23:36 UTC, Ajeyakrishna-k approved these changes

2023-10-17 02:13 UTC, ajoykumardas12 approved these changes

2023-10-17 07:27 UTC, merged

2023-10-17 08:24 UTC, kotesh-arya commented on src/app/services/idleUsersApi.ts
> +                const sortedIdleMembers = filterMembers.sort();
updated 👍🏼