Show Block Tab on Task Page of Status-site
Real-Dev-Squad/website-status pull request #960
Opened 2023-10-19 10:55 UTC by shubhamsigdar1

### Issue: #937 

### Description:

- Added Blocked Tab and blocked status in filter in status site
- Blocked Tab is under feature flag

### Dev Tested:
- [x] Yes

### Feature flag:
- [x] Yes

### Images/video of the change:

https://github.com/Real-Dev-Squad/website-status/assets/107163260/bf031644-ca69-43b3-a43f-ec128fad6048

### Test stats

<img width="733" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/107163260/5c091786-ef1a-45d4-bbb3-d8f8b600b9a5">

<img width="789" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/107163260/9b3523be-fb16-43d0-ac40-0b53693d1bdb">

<img width="745" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/107163260/9e503b23-8c56-4b80-8cf4-26b6e992d3a2">

2023-10-23 07:30 UTC, Ajeyakrishna-k approved these changes

2023-10-23 10:24 UTC, ajoykumardas12 requested changes

2023-10-23 10:24 UTC, ajoykumardas12 commented on __tests__/Unit/Components/Tasks/TaskSearch.test.tsx
> +        const searchInput = screen.getByTestId('search-input');
Is this variable used in the test?

2023-10-23 13:45 UTC, ajoykumardas12 approved these changes

2023-10-23 14:35 UTC, Ajeyakrishna-k submitted a review, later dismissed

2023-10-23 15:22 UTC, iamitprakash requested changes
Please write proper pR details

2023-10-24 03:51 UTC, ajoykumardas12 commented
Sorry @iamitprakash, missed the test stats not provided. Will be mindful of the details in future.

2023-10-24 03:52 UTC, ajoykumardas12 approved these changes
Looks good now.

2023-10-24 04:15 UTC, Ajeyakrishna-k approved these changes

2023-10-24 10:03 UTC, merged