separated files for Active and Complete
Real-Dev-Squad/website-status pull request #97
Opened 2021-03-27 06:22 UTC by aman7870

Please review made files for Active and Complete task.

2021-03-30 17:24 UTC, RohitKuwar submitted a review, later dismissed

2021-03-30 18:23 UTC, Rucha1499 reviewed
Nice work! Kindly have a look at review comment. 😃

2021-03-30 18:23 UTC, Rucha1499 commented on src/pages/completed.tsx
> +        (item: task) => item.status === 'Completed',
`Completed` in lower case?

2021-03-30 18:23 UTC, Rucha1499 commented on src/pages/active.tsx
> +        (item: task) => item.status === 'Active',
We are receiving this from the backend right? Shouldn't the value of status be in lowercase? 
![image](https://user-images.githubusercontent.com/66248039/113037269-d6ddd300-91b2-11eb-9ce8-0de6dd68980d.png)

2021-03-30 18:24 UTC, Rucha1499 commented on src/pages/completed.tsx
> +        (item: task) => item.status === 'Completed',
please refer https://github.com/Real-Dev-Squad/website-status/pull/97#discussion_r604332513

2021-03-30 19:42 UTC, whyDontI requested changes
- We do not need the accordion to display just one type of task, it'll be great if you can remove the accordion.
- Please add a message when there are no tasks available, if it is there please make sure it's working correctly
![Screenshot from 2021-03-31 01-10-35](https://user-images.githubusercontent.com/26569942/113046696-f8908780-91bd-11eb-8265-96dbe902ca94.png)

2021-04-05 03:55 UTC, aman7870 commented
Hi @whyDontI, I did change according to the requested. I have attached screenshots for changes do have a look and please 
<img width="355" alt="active" src="https://user-images.githubusercontent.com/26053172/113535391-e6b14900-95f0-11eb-826b-d58f023d3cb6.PNG">
<img width="392" alt="complete" src="https://user-images.githubusercontent.com/26053172/113535394-e9ac3980-95f0-11eb-918c-3adc1e1a7059.PNG">

review.

2021-04-05 04:39 UTC, whyDontI approved these changes
Good work @aman7870 🥳 
Thanks for the PR

2021-04-05 04:39 UTC, merged