Fix: idle page time formatting
Real-Dev-Squad/website-status pull request #970
Opened 2023-10-26 21:57 UTC by anishpawaskar

### Description:
- The idle page where we show idle users and their time/day for how long they have been idle. So to show time/day we are not using UTC time format.
- So i have added UTC time format there.

### Anthing you would like to inform the reviewer about:
- Didn't write any test cause it is not require and test are already written for card component.
### Dev Tested:
- [ ] Yes

### Images/video of the change:
![Idle Users _ Status Real Dev Squad _ Status Real Dev Squad - Google Chrome 27-10-2023 03_26_09](https://github.com/Real-Dev-Squad/website-status/assets/22213872/3c673b60-b0a7-4166-9292-9fad83952190)

2023-10-27 12:00 UTC, iamitprakash submitted a review, later dismissed

2023-10-27 12:34 UTC, shubhamsigdar1 commented on src/helperFunctions/getIdleSinceText.ts
> +    const idealDays = Math.round(differenceInHours / 24);
```suggestion
    const idleDays = Math.round(differenceInHours / 24);
```

2023-10-27 13:13 UTC, yesyash requested changes

2023-10-27 13:13 UTC, yesyash commented on src/helperFunctions/getIdleSinceText.ts
> +    if (idealDays <= 0) {
```suggestion
    if (idleDays <= 0) {
```

2023-10-27 13:13 UTC, yesyash commented on src/helperFunctions/getIdleSinceText.ts
> +    } else if (idealDays === 1) {
```suggestion
    } else if (idleDays === 1) {
```

2023-10-27 13:15 UTC, yesyash requested changes

2023-10-27 13:15 UTC, yesyash commented on src/helperFunctions/getIdleSinceText.ts
> +    return `${idealDays} days ago`;
```suggestion
    return `${idleDays} days ago`;
```

2023-10-27 13:15 UTC, yesyash commented on src/helperFunctions/getIdleSinceText.ts
> +        return `${idealDays} day ago`;
```suggestion
        return `${idleDays} day ago`;
```

2023-10-27 18:11 UTC, shubhamsigdar1 submitted a review, later dismissed

2023-10-27 18:50 UTC, Achintya-Chatterjee approved these changes

2023-10-28 20:42 UTC, yesyash approved these changes

2023-10-28 20:42 UTC, Achintya-Chatterjee approved these changes

2023-10-28 20:44 UTC, merged

2023-10-28 20:44 UTC, Achintya-Chatterjee approved these changes