Remove "COMPLETED" Option for Super User Task Creation
Real-Dev-Squad/website-status pull request #983
Opened 2023-11-01 09:15 UTC by shubhamsigdar1

### Issue:

### Description:

### Anthing you would like to inform the reviewer about:

### Dev Tested:
- [ ] Yes

### Images/video of the change:

### Follow-up Issues (if any)

2023-11-06 15:04 UTC, ajoykumardas12 commented
Please add test stats too.

> they should see only the "DONE" option in the status selection tag.

This is a bit confusing, they should see only "DONE" among "DoONE" and "COMPLETED" is better I think.

2023-11-06 16:43 UTC, shubhamsigdar1 commented
> Please add test stats too.
> 
> > they should see only the "DONE" option in the status selection tag.
> 
> This is a bit confusing, they should see only "DONE" among "DoONE" and "COMPLETED" is better I think.

Done with changes

2023-11-06 17:11 UTC, shubhamsigdar1 commented on src/components/issues/ActionForm.tsx
> +    const devMode = router.query.dev === 'true' ? true : false;
Done with changes can you please check

2023-11-07 09:17 UTC, shubhamjaintech approved these changes

2023-11-07 09:29 UTC, sahsisunny approved these changes

2023-11-07 09:31 UTC, ajoykumardas12 approved these changes

2023-11-07 15:23 UTC, iamitprakash requested changes
PR description are missing like UnderFeatureFalg and all....

2023-11-08 19:50 UTC, shubhamsigdar1 commented
> PR description are missing like UnderFeatureFalg and all....

Added

2023-11-09 06:02 UTC, iamitprakash approved these changes

2023-11-09 06:02 UTC, merged